package:
  name: pyhive
  version: {{ environ.get('GIT_DESCRIBE_TAG') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}

source:
  git_url: https://github.com/dropbox/PyHive.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - sasl
    - thrift
    - sqlalchemy

test:
  imports:
    - pyhive

about:
  home: https://github.com/cpcloud/PyHive
  license: Apache Software License
  summary: 'Python interface to Hive'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
